### PR TITLE
Create index.js

### PR DESCRIPTION
**Pull request by n1ghtc4t**

### CODE REVIEW

**Comment by n1ghtc4t** [comment]
@TotallyTriggeredTigers merge

**Comment by n1ghtc4t** [comment]
i dont want void finding out about this pr

**Comment by n1ghtc4t** [comment]
void: "OMG GODDY MADE A PULL REQUEST"

**Comment by n1ghtc4t** [comment]
pls

**Comment by rjm-codes** [comment]
mhmhmhmhmhm

**Comment by rjm-codes** [comment]
ty for src directory

**Pull request merged**
